name: pocketbase_plus
description: Pocketbase Plus is a Dart package that automates model generation for your PocketBase projects. Quick setup, less boilerplate, more time to build awesome apps!
version: 0.0.3
repository: https://github.com/seifalmotaz/pocketbase_plus
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  yaml: ^3.1.2
  pocketbase: ^0.18.1
  args: ^2.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  pb_gen: main

topics:
  - pocketbase
  - json
  - models
