name: pocketbase_plus
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  yaml: ^3.1.2
  pocketbase: ^0.18.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  pb_gen: main
